<?php

/**
 * @file
 * Contains pcx_deduction.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pcx_deduction_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pcx_deduction module.
    case 'help.page.pcx_deduction':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds deduction entity and state management logic.') . '</p>';
      return $output;

    default:
  }
}
