views.field.views_bulk_operations_bulk_form:
  type: views_field
  label: 'Views Bulk Operations'
  mapping:
    batch:
      type: boolean
      label: 'Process selected entities in a batch operation'
    batch_size:
      type: integer
      label: 'Size of the processing batch'
    form_step:
      type: boolean
      label: 'Display configuration form on a separate page'
    action_title:
      type: string
      label: 'Title of the action selector form element'
    selected_actions:
      type: ignore
      label: 'Selected actions array'
    preconfiguration:
      type: ignore
      label: 'Preliminary configuration array'
