definitions:
  contact__site_page:
    weight: -50
    menu_name: footer
    parent: ''
    enabled: false
    expanded: false
  comment__admin:
    enabled: false
    menu_name: admin
    parent: system.admin_content
    expanded: false
    weight: 0
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__logout:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: 10
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
