module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auto_username: 0
  automated_cron: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  book: 0
  breakpoint: 0
  ckeditor: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_log: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_payment_example: 0
  commerce_price: 0
  commerce_product: 0
  commerce_promotion: 0
  commerce_store: 0
  commerce_tax: 0
  commerce_wishlist: 0
  config: 0
  contextual: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  disable_html5_validation: 0
  ds: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  flexslider: 0
  flexslider_fields: 0
  flexslider_views: 0
  flickity: 0
  flickity_fields: 0
  flickity_views: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  kint: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  mailsystem: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  pcx_auth: 0
  pcx_custom: 0
  pcx_orgs: 0
  pcx_price_calc: 0
  pcx_rates: 0
  pcx_searchapi_view_breadcrumbs: 0
  pcx_user_expire: 0
  profile: 0
  rdf: 0
  redirect: 0
  remote_image: 0
  responsive_menu: 0
  role_delegation: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_views_taxonomy: 0
  sendgrid_integration: 0
  shortcut: 0
  state_machine: 0
  super_login: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  update: 0
  user: 0
  viewfield: 0
  views_field_view: 0
  views_ui: 0
  webform: 0
  webform_mailchimp: 0
  webform_ui: 0
  xmlsitemap: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  paycheck_exchange: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
